name: Build

on:
  push:
    branches:
      - main
      - stage
      - gui
      - core
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=etl_hs-osnabruck-etl
            -Dsonar.organization=etl
            -Dsonar.sources=.
            -Dsonar.python.version=3.11
            -Dsonar.language=py,js
            -Dsonar.exclusions=**/venv/**,**/tests/**,**/migrations/**,**/__pycache__/**
            -Dsonar.branch.name=${{ github.ref_name }}
