name: Flake8 Linter

on:
  push:
  pull_request:

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Install Reviewdog
      - uses: reviewdog/action-setup@v1
      - with:
      - reviewdog_version: latest

      - name: Run Flake8 with Reviewdog
        run: |
          flake8 --format=default | reviewdog -f=flake8 -name="flake8" -reporter=github-check -level=error
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
